apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-automation-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/majoferenc/demo-cicd-automation-app.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true